language: php

sudo: false

php:
  - '7.0'
  - '7.1'
  - '7.2'

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit --bootstrap test/bootstrap.php

notifications:
    on_success: never
    on_failure: always